frappe.pages["flux-theme-onboarding"].on_page_load = async function(wrapper) {
    const page = frappe.ui.make_app_page({ parent: wrapper, title: __("Flux Theme Onboarding"), single_column: true });
    page.set_secondary_action(__("Skip"), () => frappe.set_route("app"));
    const $c = $(page.body).html('<div id="flux_theme_onboarding-container"></div>').find("#flux_theme_onboarding-container");
    const B = "#8B5CF6", BL = "#EDE9FE";
    const steps = [
        { title: __("Welcome to Flux Theme"), content: (el) => { el.innerHTML = `<div style="text-align:center;padding:30px"><svg viewBox="0 0 120 120" width="120" height="120"><circle cx="60" cy="60" r="55" fill="${BL}" stroke="${B}" stroke-width="3"><animate attributeName="r" values="52;55;52" dur="3s" repeatCount="indefinite"/></circle><text x="60" y="68" text-anchor="middle" font-size="36" font-weight="bold">✨</text></svg><h3 style="color:${B};margin-top:16px">${__("Flux Theme")}</h3><p style="max-width:500px;margin:12px auto">${__("Modern Frappe Theme with bold gradients")}</p></div>`; } },
        { title: __("Bold Gradients"), content: (el) => { el.innerHTML = `<div style="text-align:center;padding:30px"><span style="font-size:3em">✨</span><h3 style="color:${B};margin-top:12px">${__("Bold Gradients")}</h3><p style="max-width:500px;margin:12px auto">${__("Learn how to use Bold Gradients in Flux Theme.")}</p></div>`; } },
        { title: __("Dynamic Animations"), content: (el) => { el.innerHTML = `<div style="text-align:center;padding:30px"><span style="font-size:3em">✨</span><h3 style="color:${B};margin-top:12px">${__("Dynamic Animations")}</h3><p style="max-width:500px;margin:12px auto">${__("Learn how to use Dynamic Animations in Flux Theme.")}</p></div>`; } },
        { title: __("Futuristic UI"), content: (el) => { el.innerHTML = `<div style="text-align:center;padding:30px"><span style="font-size:3em">✨</span><h3 style="color:${B};margin-top:12px">${__("Futuristic UI")}</h3><p style="max-width:500px;margin:12px auto">${__("Learn how to use Futuristic UI in Flux Theme.")}</p></div>`; } },
        { title: __("High Contrast"), content: (el) => { el.innerHTML = `<div style="text-align:center;padding:30px"><span style="font-size:3em">✨</span><h3 style="color:${B};margin-top:12px">${__("High Contrast")}</h3><p style="max-width:500px;margin:12px auto">${__("Learn how to use High Contrast in Flux Theme.")}</p></div>`; } },
        { title: __("RTL Support"), content: (el) => { el.innerHTML = `<div style="text-align:center;padding:30px"><span style="font-size:3em">✨</span><h3 style="color:${B};margin-top:12px">${__("RTL Support")}</h3><p style="max-width:500px;margin:12px auto">${__("Learn how to use RTL Support in Flux Theme.")}</p></div>`; } },
        { title: __("You are Ready!"), content: (el) => { el.innerHTML = `<div style="text-align:center;padding:30px"><span style="font-size:4em">🎉</span><h3 style="color:${B};margin-top:16px">${__("Onboarding Complete!")}</h3><p style="max-width:500px;margin:12px auto">${__("You are now ready to use Flux Theme. Use ❓ for help.")}</p><div style="margin-top:20px"><button class="btn btn-primary btn-lg" onclick="frappe.set_route('app')">${__("Go to Desk")}</button></div></div>`; } },
    ];
    if(frappe.visual&&frappe.visual.Storyboard) frappe.visual.Storyboard.create({container:$c[0],steps,brand_color:B,navigation:"both",showProgress:true});
    else { let h='<div style="max-width:800px;margin:0 auto;padding:20px">'; steps.forEach((s,i)=>{const d=document.createElement("div");if(s.content)s.content(d);h+=`<div style="margin-bottom:24px;padding:20px;border:1px solid var(--border-color);border-radius:12px"><h2 style="color:${B}">${s.title}</h2>${d.innerHTML||""}</div>`}); h+="</div>"; $c.html(h); }
};
